//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Psg.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Psg.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanına veri girilmesi zorunludur..
        /// </summary>
        internal static string AlanaVeriGirilmesiZorunlu {
            get {
                return ResourceManager.GetString("AlanaVeriGirilmesiZorunlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büyük değer gerekli..
        /// </summary>
        internal static string BuyukDegerGerekli {
            get {
                return ResourceManager.GetString("BuyukDegerGerekli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha sonra tekrar deneyiniz..
        /// </summary>
        internal static string DahaSonraTekrarDeneyiniz {
            get {
                return ResourceManager.GetString("DahaSonraTekrarDeneyiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem başarılı..
        /// </summary>
        internal static string IslemBasarili {
            get {
                return ResourceManager.GetString("IslemBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem gerçekleşmedi!.
        /// </summary>
        internal static string IslemGerceklesmedi {
            get {
                return ResourceManager.GetString("IslemGerceklesmedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt boş olamaz..
        /// </summary>
        internal static string KayitBosOlamaz {
            get {
                return ResourceManager.GetString("KayitBosOlamaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt bulunamadı!.
        /// </summary>
        internal static string KayitBulunamadi {
            get {
                return ResourceManager.GetString("KayitBulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanına en az {2} en fazla {1} karakter girebilirsiniz..
        /// </summary>
        internal static string MetinUzunlugu {
            get {
                return ResourceManager.GetString("MetinUzunlugu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıfırdan büyük değer gerekli..
        /// </summary>
        internal static string SifirdanBuyukDegerGerekli {
            get {
                return ResourceManager.GetString("SifirdanBuyukDegerGerekli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanına doğru bir tarih girilmelidir..
        /// </summary>
        internal static string YanlisTarih {
            get {
                return ResourceManager.GetString("YanlisTarih", resourceCulture);
            }
        }
    }
}
